<?php

use App\Models\Mortgage;
use App\Models\MortgageItem;
use App\Models\MortgageCustomer;
use App\Models\Branch;
use App\Models\Purity;
use Carbon\Carbon;
use Illuminate\Support\Str;

require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

if (!\Illuminate\Support\Facades\Schema::hasTable('categories')) {
    \Illuminate\Support\Facades\Schema::create('categories', function (\Illuminate\Database\Schema\Blueprint $table) {
        $table->id();
    });
}

$branch = Branch::first();
$purity = Purity::first();
$customers = MortgageCustomer::take(2)->get();

if (!$branch) {
    $branch = Branch::create([
        'name' => 'Main Branch',
        'code' => 'MAIN',
        'address' => '123 Main St',
        'phone' => '1234567890',
        'status' => 'active'
    ]);
}

if ($customers->isEmpty()) {
    $customer = MortgageCustomer::create([
        'branch_id' => $branch->id,
        'code' => 'CUST-' . mt_rand(100, 999),
        'name' => 'John Doe',
        'phone' => '01712345678',
        'address' => 'Dhaka',
        'status' => 'active'
    ]);
    $customers = collect([$customer]);
}

if (!$purity) {
    $purity = Purity::create([
        'name' => '22K',
        'metal_type' => 'gold',
        'percentage' => 91.6,
        'is_active' => true
    ]);
}

$statuses = ['active', 'redeemed', 'overdue', 'forfeited'];

for ($i = 1; $i <= 5; $i++) {
    $customer = $customers->random();
    $status = $statuses[array_rand($statuses)];
    
    $mortgage = Mortgage::create([
        'mortgage_no' => 'MRTG-' . date('Ymd') . '-' . str_pad(mt_rand(1, 9999), 4, '0', STR_PAD_LEFT),
        'mortgage_customer_id' => $customer->id,
        'branch_id' => $branch->id,
        'mortgage_date' => Carbon::now()->subDays(mt_rand(1, 60))->format('Y-m-d'),
        'due_date' => Carbon::now()->addDays(mt_rand(30, 90))->format('Y-m-d'),
        'principal_amount' => mt_rand(10000, 100000),
        'interest_rate' => mt_rand(1, 5),
        'interest_type' => 'monthly',
        'status' => $status,
        'notes' => 'Generated by seeder',
        'created_by' => 1,
    ]);

    MortgageItem::create([
        'mortgage_id' => $mortgage->id,
        'stock_type' => 'readymade',
        'item_name' => 'Gold Chain ' . mt_rand(1, 100),
        'metal_type' => 'gold',
        'purity_id' => $purity->id,
        'weight_unit' => 'traditional',
        'vori' => mt_rand(1, 2),
        'ana' => mt_rand(1, 15),
        'roti' => mt_rand(1, 5),
        'point' => 0,
        'gross_weight' => mt_rand(10, 25) . '.000',
        'net_weight' => mt_rand(10, 25) . '.000',
        'quantity' => mt_rand(1, 2),
        'estimated_value' => $mortgage->principal_amount * 1.5,
        'rate_per_vori' => 110000,
    ]);
    
    echo "Created Mortgage: {$mortgage->mortgage_no} for Customer {$customer->name}\n";
}

echo "Done seeding mortgages.\n";
